[package]
name = 'genewalkR'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.85'

[lib]
crate-type = ['staticlib']
name = 'genewalkR'

[profile.test]
opt-level = 3
debug = false

[dependencies]
burn = { version = "0.19.1", features = ["dataset", "train", "tch"] }
extendr-api = '0.8.1'
faer = "0.23.2"
node2vec-rs = "0.1.1"
rand = "0.9.2"
rayon = "1.11.0"
rustc-hash = "2.1.1"

[profile.release]
lto = true
codegen-units = 1

[lints.rust]
non_snake_case = "allow"
